/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGetWeatherDataRouteImport } from './routes/api/get-weather-data'
import { Route as ApiGetGeoCodeRouteImport } from './routes/api/get-geo-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetWeatherDataRoute = ApiGetWeatherDataRouteImport.update({
  id: '/api/get-weather-data',
  path: '/api/get-weather-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetGeoCodeRoute = ApiGetGeoCodeRouteImport.update({
  id: '/api/get-geo-code',
  path: '/api/get-geo-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/get-geo-code': typeof ApiGetGeoCodeRoute
  '/api/get-weather-data': typeof ApiGetWeatherDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/get-geo-code': typeof ApiGetGeoCodeRoute
  '/api/get-weather-data': typeof ApiGetWeatherDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/get-geo-code': typeof ApiGetGeoCodeRoute
  '/api/get-weather-data': typeof ApiGetWeatherDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/get-geo-code' | '/api/get-weather-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/get-geo-code' | '/api/get-weather-data'
  id: '__root__' | '/' | '/api/get-geo-code' | '/api/get-weather-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGetGeoCodeRoute: typeof ApiGetGeoCodeRoute
  ApiGetWeatherDataRoute: typeof ApiGetWeatherDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-weather-data': {
      id: '/api/get-weather-data'
      path: '/api/get-weather-data'
      fullPath: '/api/get-weather-data'
      preLoaderRoute: typeof ApiGetWeatherDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-geo-code': {
      id: '/api/get-geo-code'
      path: '/api/get-geo-code'
      fullPath: '/api/get-geo-code'
      preLoaderRoute: typeof ApiGetGeoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGetGeoCodeRoute: ApiGetGeoCodeRoute,
  ApiGetWeatherDataRoute: ApiGetWeatherDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
